### ISSUE TITLE
CPP/taskcpp/Basic_calculator.cpp

### ISSUE THREAD

**Issue by abhinavcodedeveloper** [BVP-ISTE/Hacktober2022#101]
Question is well explained in the code....Can you deal with characters...If yes then surely you can crack it
NOTE:- Screenshot of the code and output is required

**Comment by sabhisharma-ise** [comment]
Can you please assign this to me?

**Comment by akash-1107** [comment]
Please assign this to me

**Comment by sabhisharma-ise** [comment]
Hey I have done pull request #211 !

**Comment by sabhisharma-ise** [comment]
Calculator:-
![Code](https://user-images.githubusercontent.com/100849696/195985453-4431c7dc-ba2d-4af4-b332-a46fb91122a3.png)
![Output](https://user-images.githubusercontent.com/100849696/195985456-6deff260-5479-432d-afd1-05b29bac8190.png)
