### ISSUE TITLE
CPP/taskcpp/Binary_to_decimal.cpp

### ISSUE THREAD

**Issue by abhinavcodedeveloper** [BVP-ISTE/Hacktober2022#102]
Convert a Binary number to a decimal
NOTE:- Screenshot of the code and output is required

**Comment by Sakura74** [comment]
Hello assign this to me

**Comment by sabhisharma-ise** [comment]
Please assign this Issue!

**Comment by sabhisharma-ise** [comment]
Hey I have done pull request #195 !

**Comment by sabhisharma-ise** [comment]
![Code](https://user-images.githubusercontent.com/100849696/195973298-861f9a40-1a87-4584-b44c-b20f6c479d99.png)
![Output](https://user-images.githubusercontent.com/100849696/195973301-17ac787d-246f-4fc5-ac6f-194272993df6.png)
