### ISSUE TITLE
CPP/taskcpp/Countdigits.cpp

### ISSUE THREAD

**Issue by abhinavcodedeveloper** [BVP-ISTE/Hacktober2022#103]
Write a function that returns the number of times digit is found in the number.
Note:- Screenshot of the code and Output is required

**Comment by tanmaysharma17** [comment]
pls assign this to me #103 @abhinavcodedeveloper

**Comment by bhavuk-09** [comment]
Hello....Please Assign this to me

**Comment by akash-1107** [comment]
Please Assign this to me
