### ISSUE TITLE
CPP/taskcpp/Decimaltooctal.cpp

### ISSUE THREAD

**Issue by abhinavcodedeveloper** [BVP-ISTE/Hacktober2022#104]
Take N (number in decimal format). Write a function that converts it to octal format.
Note:- Screenshot of the code and output is required

**Comment by tanmaysharma17** [comment]
pls assign this issue to #104 @abhinavcodedeveloper @Vaibhavgupta05 @SohilK03  @divya520357

**Comment by Ankit-0009** [comment]
Assign this task to me.
