### ISSUE TITLE
CPP/taskcpp/Pairofroses.cpp

### ISSUE THREAD

**Issue by abhinavcodedeveloper** [BVP-ISTE/Hacktober2022#107]
Do you have a Girlfriend?😉...If yes then this question is for you...If no then also try it😂...Your want to surprise your girlfriend and how will you do that just open the task😏
NOTE:- Screenshot of the code and output is required

**Comment by akash-1107** [comment]
i don't have a girlfriend😂 so a i can get some feels working on this issue 😂 . Please assign this to me

**Comment by abhinavcodedeveloper** [comment]
noicee @akash-1107
