### ISSUE TITLE
python/task/twosum.py

### ISSUE THREAD

**Issue by vaibhav-sangwan** [BVP-ISTE/Hacktober2022#11]
Complete the task here:-
https://leetcode.com/problems/two-sum/

and provide the screenshot of the code and output on the path referenced to by the title of the issue.

**Comment by Kunal-Garg-12** [comment]
Assign this to me

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue?

**Comment by vaibhav-sangwan** [comment]
@Kunal-Garg-12 assigned, you may work on it
