### ISSUE TITLE
C\error\Factorial.c

### ISSUE THREAD

**Issue by Taanvee** [BVP-ISTE/Hacktober2022#119]
Find the errors in code and correct them.

**Comment by bhavuk-09** [comment]
Hello....Please Assign this to me

**Comment by swayamg20** [comment]
@Taanvee can you please check my PR on this issue.

**Comment by prajwald2607** [comment]
Please assign this issue to me !!

**Comment by swayamg20** [comment]
@Taanvee can you assign me this issue?
