### ISSUE TITLE
python/task/last_tuesday.py

### ISSUE THREAD

**Issue by reeba212** [BVP-ISTE/Hacktober2022#126]
Complete the given task and attach a screenshot of the code and output

**Comment by navin772** [comment]
Hi @reeba212 please assign this to me.

**Comment by navin772** [comment]
![last_tuesday](https://user-images.githubusercontent.com/98466550/196019639-33207b0e-c9b9-4233-9a2f-9609c820348d.png)
Here's the ss of the code and output.
