### ISSUE TITLE
python/task/count_letters_digits.py

### ISSUE THREAD

**Issue by reeba212** [BVP-ISTE/Hacktober2022#127]
Complete the given task and attach a screenshot of the code and output

**Comment by sabhisharma-ise** [comment]
Please assign this issue!

**Comment by OjaswiPande** [comment]
can you assign me this issue?

**Comment by vaibhav-sangwan** [comment]
@OjaswiPande assigned, you may work on it

**Comment by OjaswiPande** [comment]
@reeba212 @vaibhav-sangwan I completed my work.Please check
