### ISSUE TITLE
python/task/multiply_matrices.py

### ISSUE THREAD

**Issue by reeba212** [BVP-ISTE/Hacktober2022#128]
Complete the given task and attach a screenshot of the code and output

**Comment by Aditi-1709** [comment]
what is this "#!/usr/bin/env python" as my code works perfectly fine w/o it.

**Comment by reeba212** [comment]
> what is this "#!/usr/bin/env python" as my code works perfectly fine w/o it.

Hey, it's just a comment that gets added automatically when I download a python file from google collaboratory, don't worry about it :)

**Comment by Aditi-1709** [comment]
So can I remove it as my code isn't working with it ?

**Comment by reeba212** [comment]
Yes you can
