### ISSUE TITLE
python/task/sqrt_x.py

### ISSUE THREAD

**Issue by vaibhav-sangwan** [BVP-ISTE/Hacktober2022#132]
Complete the task here:-
https://leetcode.com/problems/sqrtx/

and provide the screenshot of the code and output on the path referenced to by the title of the issue.

**Comment by sabhisharma-ise** [comment]
Please this to assign!

**Comment by TanyaSri-23** [comment]
Hey! Can you please assign this issue to me

**Comment by Parth-2609** [comment]
<img width="264" alt="image" src="https://user-images.githubusercontent.com/103762350/196002618-4a01cd70-f69d-408f-8b2d-4067e9d8fd13.png">
<img width="262" alt="image" src="https://user-images.githubusercontent.com/103762350/196002625-00db49e4-dbc0-4cf1-97ea-6079b7ae6e1a.png">
Completed the issue

**Comment by Parth-2609** [comment]
<img width="239" alt="image" src="https://user-images.githubusercontent.com/103762350/196002933-c3593ab3-1cc4-4aaa-9847-f2c757ec5c7f.png">
<img width="233" alt="image" src="https://user-images.githubusercontent.com/103762350/196002970-ae230c6e-edda-4e6e-8b72-f607956290fc.png">
Completed the issue and also sent the PR.

**Comment by vaibhav-sangwan** [comment]
@Parth-2609 open the PR

**Comment by TanyaSri-23** [comment]
Completed the task

<img width="569" alt="image" src="https://user-images.githubusercontent.com/76212920/196209361-8981891a-1e3a-4956-842b-f42aecc6fddf.png">
<img width="541" alt="image" src="https://user-images.githubusercontent.com/76212920/196209625-defe559d-64cd-4a45-a66c-61d7b1659a36.png">
<img width="382" alt="image" src="https://user-images.githubusercontent.com/76212920/196209709-5764d1f4-ce9c-4048-9fc6-beb6c6e24ede.png">

**Comment by Parth-2609** [comment]
@vaibhav-sangwan sorry for the inconvenience 
I opened the PR again
