### ISSUE TITLE
python/task/remove-duplicates-from-sorted-list.py

### ISSUE THREAD

**Issue by vaibhav-sangwan** [BVP-ISTE/Hacktober2022#134]
Complete the task here:-
https://leetcode.com/problems/remove-duplicates-from-sorted-list/

and provide the screenshot of the code and output on the path referenced to by the title of the issue.

**Comment by sabhisharma-ise** [comment]
Please assign this issue!

**Comment by vaibhav-sangwan** [comment]
@sabhisharma-ise assigned, you may work on it

**Comment by sabhisharma-ise** [comment]
I should paste the screenshot of the code with output (leetcode platform) in the folder directly right?

**Comment by vaibhav-sangwan** [comment]
@sabhisharma-ise there are merge conflicts in the Pull Request. close the PR, pull the latest code from this repo, push your code in the newly pulled repo, and then make a PR.
