### ISSUE TITLE
python/task/merge-sorted-array.py

### ISSUE THREAD

**Issue by vaibhav-sangwan** [BVP-ISTE/Hacktober2022#135]
Complete the task here:-
https://leetcode.com/problems/merge-sorted-array/

and provide the screenshot of the code and output on the path referenced to by the title of the issue.

**Comment by akash-1107** [comment]
Please assign this to me

**Comment by vaibhav-sangwan** [comment]
@akash-1107 assigned, you may work on it

**Comment by OjaswiPande** [comment]
can you assign me this issue?

**Comment by vaibhav-sangwan** [comment]
@OjaswiPande assigned

**Comment by OjaswiPande** [comment]
Sorry Because of some issues I can't do it.
