### ISSUE TITLE
CPP/error/oddevencharacter.cpp

### ISSUE THREAD

**Issue by abhinavcodedeveloper** [BVP-ISTE/Hacktober2022#141]
Find out the error in the code
NOTE:- Screenshot of the code and output is required

**Comment by officialasishkumar** [comment]
Hello! would love to work on this issue :-)

**Comment by abhinavcodedeveloper** [comment]
Sure go ahead @officialasishkumar

**Comment by bhavuk-09** [comment]
Hello.... Assign this to me

**Comment by abhinavcodedeveloper** [comment]
Sure @bhavuk-09
