### ISSUE TITLE
CPP/error/toggle.cpp

### ISSUE THREAD

**Issue by abhinavcodedeveloper** [BVP-ISTE/Hacktober2022#145]
Find out the error in the code
NOTE:- Screenshot of the code and output is required

**Comment by chiragcode11** [comment]
can I work on this issue

**Comment by abhinavcodedeveloper** [comment]
go ahead
@chiragcode11

**Comment by AK-shat-JAIN** [comment]
I can Do this task

**Comment by chiragcode11** [comment]
is this closed ?
