### ISSUE TITLE
C\task\Root.c

### ISSUE THREAD

**Issue by Taanvee** [BVP-ISTE/Hacktober2022#146]
Complete the given task and attach a screenshot of the code and output

**Comment by swayamg20** [comment]
can you please assign me this issue?

**Comment by Taanvee** [comment]
Yes go ahead

**Comment by swayamg20** [comment]
I made a PR can you please check it?

**Comment by sabhisharma-ise** [comment]
Please assign this issue!

**Comment by prajwald2607** [comment]
Please assign this issue to me !!
