### ISSUE TITLE
C\task\Palindrome.c

### ISSUE THREAD

**Issue by Taanvee** [BVP-ISTE/Hacktober2022#147]
Complete the given task and attach a screenshot of the code and output

**Comment by Prashant1308** [comment]
@Taanvee  can you assign it to me?

**Comment by sabhisharma-ise** [comment]
Please assign this issue!

**Comment by swayamg20** [comment]
@Taanvee Can you please check my PR?

**Comment by prajwald2607** [comment]
Please assign this issue to me !!
