### ISSUE TITLE
C++\error\bubblesort.cpp

### ISSUE THREAD

**Issue by abhinavcodedeveloper** [BVP-ISTE/Hacktober2022#2]
the given array is sorted using bubble sort algorithm but there is an error...find the error in the code to make it work
NOTE:- Screenshot of the code and output is required

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue?

**Comment by prajwald2607** [comment]
Please assign this issue to me !!

**Comment by swayamg20** [comment]
can you assign me this issue?
