### ISSUE TITLE
python/task/pascals_triangle.py

### ISSUE THREAD

**Issue by reeba212** [BVP-ISTE/Hacktober2022#23]
Complete the task and attach a screenshot of your code and output. You may take the input yourself according to the task.

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue?

**Comment by OjaswiPande** [comment]
can you assign me this issue?

**Comment by sabhisharma-ise** [comment]
Done this code PR #225 !

**Comment by sabhisharma-ise** [comment]
@reeba212 PR #225
