### ISSUE TITLE
python/task/ransom_note.py

### ISSUE THREAD

**Issue by reeba212** [BVP-ISTE/Hacktober2022#24]
Complete the task and attach a screenshot of your code and output. You may take the input yourself according to the task.

**Comment by navin772** [comment]
@reeba212 I have solved this issue and opening a PR for the same. Please review!
![ransom_note](https://user-images.githubusercontent.com/98466550/196034879-fa244282-39bb-46f5-97f0-4f665b176a1e.png)

**Comment by KrishKumar3004** [comment]
Hey! I would like to contribute. Please assign it to me.

**Comment by reeba212** [comment]
> Hey! I would like to contribute. Please assign it to me.

Hey! Sorry, this issue has already been solved
