### ISSUE TITLE
CPP/error/binarySearch.cpp

### ISSUE THREAD

**Issue by ela2003** [BVP-ISTE/Hacktober2022#31]
rectify the error in the code.
NOTE:- Screenshot of the code and output is required.

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue?

**Comment by OjaswiPande** [comment]
can you assign me this issue?

**Comment by Animeshkr001** [comment]
can you please assign me this issue ?

**Comment by sabhisharma-ise** [comment]
Done with PR #303 !
