### ISSUE TITLE
CPP/error/findminandmaxinarray.cpp

### ISSUE THREAD

**Issue by ela2003** [BVP-ISTE/Hacktober2022#36]
rectify the error in the code.
NOTE:- Screenshot of the code and output is required.

**Comment by abhinavmaheshwari03** [comment]
I want to work on this issue..Please assign it to me

**Comment by bhavuk-09** [comment]
Hello....Please Assign this to me

**Comment by akash-1107** [comment]
Please Assign this to me

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue?
