### ISSUE TITLE
C++\error\pallindrome.cpp

### ISSUE THREAD

**Issue by abhinavcodedeveloper** [BVP-ISTE/Hacktober2022#4]
in the given code it is checked whether the given string is a pallindrome or not
for eg:- abba
output:- Pallindrome
Find the error in the code
NOTE:- Screenshot of the code and output is required

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue?

**Comment by akash-1107** [comment]
Please assign this to me @abhinavcodedeveloper

**Comment by swayamg20** [comment]
can you assign me this issue? @abhinavcodedeveloper
