### ISSUE TITLE
C++\error\GCD.cpp

### ISSUE THREAD

**Issue by abhinavcodedeveloper** [BVP-ISTE/Hacktober2022#42]
Question is well explained in the code...Find the error to resolve the problem
It's an easy one...I am sure you will crack it.🚀
NOTE:- Screenshot of the code and output is required

**Comment by chiragcode11** [comment]
can you assign me this issue

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue?

**Comment by swayamg20** [comment]
can you assign me this issue?
