### ISSUE TITLE
CPP/taskcpp/ComplementOfBase10.cpp

### ISSUE THREAD

**Issue by ela2003** [BVP-ISTE/Hacktober2022#47]
Complete the task and attach a screenshot of your code and output. You may take the input yourself according to the task.

**Comment by bhoomikhurana** [comment]
<img width="1440" alt="Screenshot 2022-10-16 at 6 13 57 PM" src="https://user-images.githubusercontent.com/96761198/196036414-b7c0dfac-16f9-46d6-a0b6-8eeda44356e6.png">

**Comment by Aritra056GITHUB** [comment]
Please assign me this task I am sure I can do it.

**Comment by bhoomikhurana** [comment]
Pls assign this task to me
