### ISSUE TITLE
CPP/taskcpp/PowerofTwo.cpp

### ISSUE THREAD

**Issue by ela2003** [BVP-ISTE/Hacktober2022#54]
Complete the task and attach a screenshot of your code and output. You may take the input yourself according to the task.

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue?

**Comment by OjaswiPande** [comment]
can you assign me this issue?

**Comment by sabhisharma-ise** [comment]
@ela2003 Done with PR #302 !
