### ISSUE TITLE
CPP/taskcpp/ReverseName.cpp

### ISSUE THREAD

**Issue by ela2003** [BVP-ISTE/Hacktober2022#56]
Complete the task and attach a screenshot of your code and output. You may take the input yourself according to the task.

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue?

**Comment by prajwald2607** [comment]
Please assign this issue to me !!

**Comment by prajwald2607** [comment]
Check pull request

# include <iostream>
# include <string>
using namespace std;
int main()

{
char fname[30], lname [30];
 cout << "\n\n Print the name in reverse where last name comes first:\n";
 cout << "-----------------------------------------------------------\n";
cout << " Input First Name: ";
cin >> fname;
cout << " Input Last Name: ";
cin >> lname;

cout << " Name in reverse is: "<< lname << " "<< fname <<endl;
	cout << endl;
return 0;
}
Output: 
![reversename](https://user-images.githubusercontent.com/78312896/196896625-4de9a4ac-082d-435e-828d-56834b894fbf.png)
