### ISSUE TITLE
CPP/taskcpp/SearchElement.cpp

### ISSUE THREAD

**Issue by ela2003** [BVP-ISTE/Hacktober2022#57]
Complete the task and attach a screenshot of your code and output. You may take the input yourself according to the task.

**Comment by abhinavmaheshwari03** [comment]
I want to work on this issue..please assign it to me

**Comment by abhinavmaheshwari03** [comment]
Do i have to return boolean value,index or the element??

**Comment by ela2003** [comment]
> Do i have to return boolean value,index or the element??

you have to find the index at which the element is present in array

**Comment by abhinavmaheshwari03** [comment]
Completed the task...please review it
