### ISSUE TITLE
CPP/taskcpp/Importance_of_time.cpp

### ISSUE THREAD

**Issue by abhinavcodedeveloper** [BVP-ISTE/Hacktober2022#62]
How important time is for you will get the solution of this question😂...
Coming to the question...It's a DSA one...try to figure out how you end to the output...question is well explained in the code
HINT:- Queues laga ke dekhna😊
NOTE:- **Screen shot of the code and output is required**

**Comment by OjaswiPande** [comment]
can you assign me this question?
