### ISSUE TITLE
C++\error\reversearray.cpp

### ISSUE THREAD

**Issue by abhinavcodedeveloper** [BVP-ISTE/Hacktober2022#7]
Reverse the array 
inp -- >  1234
out -- >  4321
Find the error in the code🚀
NOTE:- Screenshot of the code and output is required

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue?

**Comment by prajwald2607** [comment]
Please assign this issue to me !!

**Comment by swayamg20** [comment]
can you please assign me this issue?

**Comment by abhinavcodedeveloper** [comment]
This issue is already assigned to someone...try new

**Comment by sabhisharma-ise** [comment]
Hey, I have resolved the error in the reversearray.cpp file. It now works correctly! Please check my PR #300
