### ISSUE TITLE
C++\error\rightview.cpp

### ISSUE THREAD

**Issue by abhinavcodedeveloper** [BVP-ISTE/Hacktober2022#8]
take input:- 1 2 3 4 5 -1 -1 6 7 8 9 -1 -1 10 11 -1 -1 -1 -1 -1 -1 -1 -1
output:- 1 3 5 9 11
this is the right view of a tree..imagine the tree by yourself and find the error
NOTE:- Screenshot of the code and output is required

**Comment by Animeshkr001** [comment]
can you please assign me this issue ??
