### ISSUE TITLE
python/task/palindrome_number.py

### ISSUE THREAD

**Issue by vaibhav-sangwan** [BVP-ISTE/Hacktober2022#83]
Complete the task here:-
https://leetcode.com/problems/palindrome-number/

and provide the screenshot of the code and output on the path referenced to by the title of the issue.

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue?

**Comment by kartik77041** [comment]
![image](https://user-images.githubusercontent.com/92300157/197153409-741c2eef-7fab-4368-9248-f4522d16d796.png)
