### ISSUE TITLE
python/task/longest_common_prefix.py

### ISSUE THREAD

**Issue by vaibhav-sangwan** [BVP-ISTE/Hacktober2022#84]
Complete the task here:-
https://leetcode.com/problems/longest-common-prefix/

and provide the screenshot of the code and output on the path referenced to by the title of the issue.

**Comment by reeba212** [comment]
![longestprefix](https://user-images.githubusercontent.com/64488642/196179134-9cca6e08-56eb-4475-99df-795d04ee2137.PNG)
