### ISSUE TITLE
python/task/remove-duplicates-from-sorted-array.py

### ISSUE THREAD

**Issue by vaibhav-sangwan** [BVP-ISTE/Hacktober2022#86]
Complete the task here:-
https://leetcode.com/problems/remove-duplicates-from-sorted-array/

and provide the screenshot of the code and output on the path referenced to by the title of the issue.

**Comment by kartik77041** [comment]
![image](https://user-images.githubusercontent.com/92300157/197153901-16a0c61d-be6d-4e6b-82b9-22370336f5d6.png)

**Comment by kartik77041** [comment]
please assign!!

**Comment by vaibhav-sangwan** [comment]
@kartik77041 assigned, you may work on it
