### ISSUE TITLE
python/task/remove-element.py

### ISSUE THREAD

**Issue by vaibhav-sangwan** [BVP-ISTE/Hacktober2022#87]
Complete the task here:-
https://leetcode.com/problems/remove-element/

and provide the screenshot of the code and output on the path referenced to by the title of the issue.

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue?

**Comment by kartik77041** [comment]
![image](https://user-images.githubusercontent.com/92300157/197170363-f2db98a8-4a90-4ea3-8ff9-96af65097393.png)
