### ISSUE TITLE
python/error/common_element.py

### ISSUE THREAD

**Issue by reeba212** [BVP-ISTE/Hacktober2022#90]
Find the errors in the code and correct them

**Comment by navin772** [comment]
@reeba212 I solved this issue and now the code works perfectly! Please review
![common_element](https://user-images.githubusercontent.com/98466550/196035631-6e9922b1-3bc9-4576-826a-a6d73519b33e.png)

**Comment by reeba212** [comment]
> @reeba212 I solved this issue and now the code works perfectly! Please review
> ![common_element](https://user-images.githubusercontent.com/98466550/196035631-6e9922b1-3bc9-4576-826a-a6d73519b33e.png)
> 

Great! Make sure to start a pull request with the changes you made in the code
