### ISSUE TITLE
python/error/filter_vowels.py

### ISSUE THREAD

**Issue by reeba212** [BVP-ISTE/Hacktober2022#91]
Find the errors in the code and correct them

**Comment by navin772** [comment]
@reeba212 please assign this issue to me!

**Comment by navin772** [comment]
![filter_vowels](https://user-images.githubusercontent.com/98466550/196034117-f34ffc01-2be2-4e87-b7f8-3d4f1d0c5f61.png)
Here you go @reeba212  . Thanks for the reminder

**Comment by KrishKumar3004** [comment]
Hey! I would like to contribute. Please assign it to me.

**Comment by reeba212** [comment]
> Hey! I would like to contribute. Please assign it to me.

Hey! Sorry but this issue has already been solved
