### ISSUE TITLE
python/error/all_prime_nums.py

### ISSUE THREAD

**Issue by reeba212** [BVP-ISTE/Hacktober2022#93]
Find the errors in the code and correct them

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue?

**Comment by reeba212** [comment]
> Can you please assign this issue?

Hey, I've assigned this issue to you!

**Comment by sabhisharma-ise** [comment]
> > Can you please assign this issue?
> 
> Hey, I've assigned this issue to you!

Thanx!

**Comment by sabhisharma-ise** [comment]
The code is working properly already!
all_prime_nums.py
