### ISSUE TITLE
python/error/anagram.py

### ISSUE THREAD

**Issue by reeba212** [BVP-ISTE/Hacktober2022#99]
Find the errors in the code and correct them

**Comment by Divyessh** [comment]
@reeba212
Please check the PR opened for this issue, and let me know if any changes or modification is needed.
Thanks.

**Comment by reeba212** [comment]
> @reeba212
> Please check the PR opened for this issue, and let me know if any changes or modification is needed.
> Thanks.

Hey! You're also required to attach a screenshot of the code and output here.

**Comment by Divyessh** [comment]
> > @reeba212
> > Please check the PR opened for this issue, and let me know if any changes or modification is needed.
> > Thanks.
> 
> Hey! You're also required to attach a screenshot of the code and output here.

Sure, here are the relevant screenshots.
![screenshot_1](https://user-images.githubusercontent.com/67703282/196024365-3136cd7a-6ceb-4b74-8276-eaefbef67a8b.png)
![screenshot_2](https://user-images.githubusercontent.com/67703282/196024368-d3e9295e-4595-4f05-8fca-7ae702aadc05.png)
